---
bibliography: references.bib
---

# Research background {#sec-lit}

Over the past few decades, reducing the unmet need for contraceptives has been a central focus in the field of FPSC [@mukasa2017]. This issue has been recognized as a critical agenda item in achieving the 2030 Sustainable Development Goals, particularly in expanding access to contraception to ensure universal access to family planning services [@kantorova2021]. Consequently, accurate and reliable demand forecasting plays a crucial role in the FPSC, as it supports informed decision making processes to ensure access to safe and effective contraceptives, thereby empowering individuals and communities to make informed reproductive health choices [@ahmed2019].

The majority of literature on forecasting in the FPSC has centered on estimating family planning indicators at national or global levels to guide strategic decisions. For instance, @ahmed2019 employed linear and quadratic logistic regression methods to estimate the modern contraceptive prevalence rate (mCPR)[^1] in five sub-Saharan African countries, using data from the PMA2020 survey. Similarly, @new2017 examined trends in three family planning indicators; 1) mCPR, 2) unmet demand for modern contraceptives, and 3) demand satisfied by modern contraceptives. Their study covered the period from 1990 to 2030 for 29 states and union territories in India. To conduct their analysis, they employed a Bayesian hierarchical method, integrating statistical time-series techniques with demographic factors drawn from the Demographic Health Survey (DHS) [@DHSProgram], Annual Health Survey, and District-Level Household Survey. @haakenstad2022 used a spatio-temporal Gaussian process regression method to estimate mCPR, method mix, and demand satisfied for the global contraceptive prevalence rate between 1970 and 2019.

[^1]: The estimation of the percentage of women using a modern contraceptive product [@ahmed2019].

These national and global-level studies provide valuable strategic insights into contraceptive coverage and trends. However, they were not designed to address operational realities at local levels, such as variations in demand and supply chain issues at individual service delivery points. Their focus remains on broader, aggregate-level decisions that inform national or global policies and strategies [@new2017]. Thus, while these studies may not capture the granular, site-specific challenges at the operational level, their contributions are still highly valuable for higher-level planning and resource allocation.

On the other hand, a fewer have addressed national-level forecasts for specific contraceptive products. For instance, @akhlaghi2013 estimated national demand for condoms using demographic-based forecasting and a consumption-based moving average method, incorporating expert judgment to refine predictions. @karanja applied consumption-based forecasting using Auto Regressive Integrated Moving Average (ARIMA) and exponential smoothing methods to estimate demand for contraceptive pills, injectables, implants, and intrauterine contraceptive devices (IUDs), using data from Kenya's District Health Information System (DHIS). Moreover, @khan2015 used a demographic-based forecasting approach integrating expert assumptions with DHS data to estimate demand for *Sayana Press*, a new injectable contraceptive, across 12 countries. These studies also reflect a focus on national or strategic decision-making.

However, at the operational level, where service delivery occurs, forecasting must account for uncertainties and variations specific to each location. In contrast to aggregate studies that often incorporate probabilistic forecasting, which includes prediction intervals to manage uncertainty [@new2017; @ahmed2019; @haakenstad2022], operational studies like @akhlaghi2013 and @karanja primarily used point forecasts. These point forecasts provide a single estimate without explicitly addressing the uncertainty surrounding the forecasted values. In dynamic settings such as healthcare service delivery, this can limit their applicability. Operational-level contexts often experience demand variations due to factors like stockouts, local preferences, and seasonal changes [@mukasa2017].

Probabilistic forecasts, which include a range of possible outcomes (such as prediction intervals), are crucial in such contexts because they acknowledge the uncertainty and help supply chain managers make more informed decisions [@rostami-tabar2024]. For example, @khan2015 utilized scenario analysis to acknowledge forecast uncertainty for the injectable contraceptive Sayana Press in 12 countries. However, in the works of @akhlaghi2013 and @karanja, only point predictions were generated, with no explicit consideration of uncertainty in the forecasts. This omission potentially limits the applicability of their findings in dynamic operational contexts, as point forecasts, which provide a single value estimate, are simpler but less adaptable to fluctuating demand conditions.

In practice, however, many still rely on simple methods to produce point forecasts, despite the limitations these approaches present in capturing the demand variations for each contraceptive product. [@altay2022]. These methods often fail to address the complexity of demand and attempt to answer multiple questions using point forecasts [@lacroix2023]. The most commonly employed methods include: 1) extrapolating historical consumption using basic time series methods, linear trends, averages, or simple regression methods; 2) estimating consumption based on service statistics, such as program plans; and 3) utilizing population demographics to project demand [@familyplanninglogisticsmanagement2000]. In practice, however, many supply chain managers still rely on point forecasts due to their simplicity, despite the limitations of these approaches in accounting for demand fluctuations at the local level [@altay2022]. Common methods include basic time series methods, linear trends, and demographic-based projections [@familyplanninglogisticsmanagement2000]. While these methods are easy to implement, they often overlook critical uncertainties and the complexities of real-world contraceptive demand, such as external shocks (e.g., global crises like COVID-19), demand shifts due to market cannibalization, or supply chain disruptions [@lacroix2023].

As a result, these simplistic forecasting approaches can lead to inefficiencies in ordering and distribution, causing stockouts or overstocking at healthcare sites, ultimately impairing access to essential contraceptive services [@mukasa2017]. This underscores the need for more advanced forecasting methods that incorporate both uncertainty and local variations in demand to optimize supply chain performance and support better family planning outcomes [@Baker2022].

## USAID Intelligent Forecasting Competition

The USAID Intelligent Forecasting Competition attempted to address the need for a more reliable contraceptive demand forecasting method by inviting participants to develop intelligent forecasting methods. Specifically, participants were tasked with forecasting contraceptive consumption at the service delivery level of Côte d'Ivoire's public sector health system over a three-month forecast horizon, using data provided from the Cote d’Ivoire public health system to forecast the consumption of contraceptives over three months. This competition attracted nearly 80 submissions from 40 participants, reflecting a diverse range of forecasting approaches [@USAID2020].

The winning entry in the USAID Intelligent Forecasting Competition, developed by Inventec Corporation, used distinct models for each forecasting horizon. They employed both LightGBM and Long Short-Term Memory (LSTM) methods, incorporating categorical features, historical data, and future population projections. The final forecast was derived from an ensemble of these methods, with weights assigned differently for each forecasting horizon.

The second-place model employed an ensemble approach, averaging the predictions from six separate LightGBM models, each designed for a specific forecasting horizon. This strategy reflects a robust method for improving forecast accuracy through aggregation. The third-best model also used LightGBM but incorporated hyperparameter tuning and additional trend indicators, such as linear and polynomial functions, alongside various time-series features.

Another notable submission employed hierarchical forecasting with a bottom-up approach, using ARIMA (AutoRegressive Integrated Moving Average) as the base forecasting method. This method demonstrates the utility of hierarchical techniques in complex forecasting scenarios. Additionally, a model that combined neural networks with a naive forecasting approach was also among the top contenders. For longer time series, this model used an ensemble of predictions from different neural network architectures, including Convolutional Neural Networks (CNN), Gated Recurrent Units (GRU), and LSTMs, with the final prediction being the median of these forecasts. For shorter time series, it used a naive Bayes method. @tbl-literature presents a summary of the top 10 submissions in the competition[^2].

[^2]: In this table, the term global forecasting refers to a method where a single model is developed to handle all time series, while cross-validation refers to a technique where the forecasting origin is moved forward by a fixed number of steps, producing multiple forecasts at different points in time.

Although the competition significantly advanced forecasting methodologies, it primarily concentrated on point forecasts, with limited attention to the quantification of forecast uncertainty. Since the competition's objectives did not explicitly include probabilistic forecasting, criticising these methods for overlooking uncertainty may be unwarranted. Nevertheless, incorporating uncertainty measures is crucial for improving forecast reliability, as decision-makers in the field require dynamic estimates that reflect the uncertainties associated with contraceptive demand over time [@lacroix2023]. The absence of standard approaches for incorporating uncertainty into forecasts highlights a significant gap. While the competition represented a significant step towards the development of advanced forecasting methodologies, it did not fully address the need for probabilistic estimations that can better inform decision making by accounting for forecast variability.

## Human judgment in contraceptive demand forecasting

In reality, uncertainties in contraceptive demand arise from complex patterns of product availability, variable lead times, and the overreliance of donor support [@mircetic2022]. These uncertainties are further complicated by inadequacies in data collection, storage, and sharing practices. Despite the implementation of Logistics Management Information Systems (LMIS), field operatives frequently depend on paper-based forms and Excel spreadsheets for data collection and operational management [@devries2020]. This reliance on outdated methods often results in noisy, inaccurate, and incomplete data, thereby complicating the forecasting efforts [@besiou2020]. Moreover, stockout driven consumption data may not reflect actual demand, further distorting the forecasting process [@deboeck2023].

Forecasting algorithms, while adept at processing high-dimensional data, may struggle to detect these sudden fluctuations and discontinuities in contraceptive demand [@hong2021]. Thus, this leaves the expert to use their contextual knowledge to understand the context of the data and incorporate it with the forecasting process [@hong2021]. Previous literature also suggests that experts can improve the forecast performance when the external information has not been added to the algorithm-based forecasting method using their inside knowledge and expertise[^3] [@fildes2007; @davydenko2013].

[^3]: See @perera2019 for a detailed review on human factors in supply chain forecasting.

In the context of FPSC in developing countries, current algorithm-based forecasting methods possess the capability to manage extensive datasets, including thousands of time series across diverse geographies simultaneously [@hong2021]. However, these algorithms may not fully account for external factors and contextual nuances that experts are adept at identifying [@devries2020]. This suggests that integrating human expertise with algorithm-based forecasts could yield more reliable and accurate predictions. Empirical evidence also supports the notion that combining human judgment with algorithmic forecasts enhances forecast performance [@fildes2009; @petropoulos2018]. Furthermore, literature shows that such forecast combinations improve forecasting accuracy compared to using either method in isolation [@wang2023]. This leads to the critical question of how best to integrate human expertise with algorithm-based forecasting.

Various approaches exist for integrating human judgment with algorithmic forecasts, forming hybrid intelligence systems that leverage the strengths of both. @brau2023 categorize these methods into five key types:

-   *Judgmental Adjustment* – Experts modify algorithmic forecasts based on contextual insights.
-   *Quantitative Correction* – Systematic adjustments are applied to human forecasts using statistical techniques.
-   *Forecast Combination* – Separate judgmental and algorithm-based forecasts are merged into a single forecast.
-   *Judgment as a Model Input* – Expert knowledge is incorporated as a predictive variable within the forecasting model.
-   *Integrative Judgment Learning* – Human inputs iteratively refine model predictions through a structured learning process.

Judgmental adjustments have been widely studied in supply chain contexts, particularly in promotional settings. @trapero2013 found that structured human interventions during promotions improved forecasting accuracy. This aligns with findings from @fildes2015, who argue that human adjustments enhance reliability when bias is minimized.

Quantitative correction methods offer a structured way to adjust forecasts while maintaining statistical integrity. @fildes2009 highlight the importance of systematic corrections to mitigate bias and improve forecast accuracy.

Forecast combination has been explored as a way to merge expert forecasts with algorithmic outputs. @goodwin2000 highlights its effectiveness in capturing both statistical trends and domain knowledge, making it a useful technique when expert input is available alongside data-driven predictions.

Another structured approach to integrating expert knowledge into forecasting models is treating human judgment as a direct input to model-building. Instead of adjusting forecasts post hoc, this method incorporates expert-driven insights as predictive variables, allowing the model to factor in domain knowledge systematically. @arvan2019 suggest that using expert judgment as a model input can improve forecasting accuracy, particularly in cases where statistical models alone struggle to capture contextual nuances. By embedding domain expertise within the forecasting process, this approach ensures that human insights are systematically integrated, rather than relying on manual interventions.

On the other hand, integrative Judgment Learning @baecke2017, @brau2023 treat human adjustments as predictive variables, allowing models to systematically weigh their impact. Similarly, @goodwin1999 suggest that hybrid forecasting models should be designed to correct systematic biases in human judgment while maintaining adaptability.

Some studies explore hybrid forecasting methods that do not fit neatly into a single category. These approaches often involve adaptive weighting mechanisms, optimization-driven model adjustments, or learning-based frameworks that dynamically integrate human and machine-generated forecasts [@petropoulos2022]. While not explicitly categorized under the five methods, these strategies contribute to the broader understanding of how expert judgment and algorithmic forecasts can be effectively combined.

In this context, two key considerations arise when selecting an approach for combining forecasts: 1) healthcare staff at the site level in developing countries often lack the specialized skills and training needed to develop and maintain sophisticated forecasting methods [@altay2022], and 2) based on discussions with USAID officials, healthcare staff typically produce only point forecasts, often relying on their judgment, as also highlighted in the literature [@akhlaghi2013]. Moreover, @lacroix2023 found that although practitioners acknowledge the importance of accounting for uncertainty, there is no widely adopted standard for doing so. Judgmental point forecasts are favored because they align with the practical experience and cognitive abilities of healthcare staff, who may find it difficult to quantify uncertainty without formal training in probabilistic ms. Given these constraints, combining human judgmental forecasts with algorithmic forecasts presents a promising solution. Empirical studies consistently show that combining forecasts, whether judgmental or model-based, generally improves accuracy over relying on individual forecasts alone [@ranjan; @wang2023]. However, this introduces a challenge: how to effectively integrate human point forecasts with probabilistic forecasts from algorithms to produce a unified probabilistic forecast. Although the literature on forecast combinations is extensive, little attention has been paid to the integration of point forecasts with probabilistic forecasts.^[See @wang2023 for a comprehensive review.]

## Literature limitations summary

Despite advancements in contraceptive demand forecasting, several key gaps remain unaddressed. First, the use of probabilistic forecasting in FPSC remains limited. While probabilistic methods have been widely explored in other domains, such as economic forecasting [@gneiting2014; @krüger2017], their application in FPSC is largely absent. Most existing studies rely on point forecasts, which do not account for demand uncertainty, making supply chain planning more vulnerable to unexpected fluctuations. Given the inherent unpredictability of contraceptive demand, incorporating probabilistic forecasting is critical for improving stock management and mitigating stockout risks.

Second, contraceptive demand forecasting has primarily been conducted at the national or regional level [@akhlaghi2013; @karanja], often overlooking demand variability at individual healthcare sites. However, demand patterns vary significantly across locations [@karimi2021], and without localized forecasts, procurement decisions may fail to align with actual site-level needs. This highlights the need for forecasting approaches that can adapt to site-specific demand while maintaining consistency with broader supply chain strategies.

Third, while forecast combination techniques have been extensively studied [@ranjan], their application in FPSC is underexplored. Existing studies typically assess individual forecasting methods without considering how integrating multiple forecasts could improve accuracy, particularly in healthcare supply chains. Additionally, there is limited empirical research comparing different forecasting methods for contraceptive demand estimation, making it difficult to determine the most effective approach in this context.

Finally, although judgmental adjustments are widely used in FPSC [@fildes2009; @trapero2013], there is no structured approach that systematically integrates expert knowledge while ensuring coherence between human forecasts and probabilistic distributions in FPSC settings. In economic forecasting, Entropic Tilting has been used to refine probabilistic distributions based on external point forecasts [@krüger2017; @metaxoglou2016], yet these methods do not explicitly ensure coherence between expert judgment and forecast distributions. Our study addresses this gap by proposing a hybrid forecasting approach that systematically integrates expert forecasts with probabilistic models, ensuring that adjustments remain statistically grounded while incorporating expert insights.

```{r}
#| label: tbl-literature
#| echo: false
#| cache: false
#| tbl-cap: "Summary of the top 10 models in the USAID intelligent forecasting competition."

library(kableExtra)

readxl::read_xlsx(here::here("manuscript/phd_wp1_hybrid_model/tables/lr_table.xlsx")) |>
  knitr::kable(booktabs = T, linesep = "") |>
  kable_styling(latex_options = "scale_down", font_size = 9) |>
  column_spec(1, "8em") |>
  column_spec(2, "18em") |>
  column_spec(3, "6em") |>
  column_spec(4, "9em") |>
  column_spec(5, "6em") |>
  column_spec(6, "6em") |>
  column_spec(7, "6em") |>
  landscape()

```
